// generated by https://next.json-generator.com/E11epG5UB

export const actorsData = [
    {
        "name": "Carroll Kemp",
        "age": 33,
        "type": "student"
    },
    {
        "name": "Hollie Guthrie",
        "age": 35,
        "type": "student"
    },
    {
        "name": "Hooper Marrien",
        "age": 32,
        "type": "student"
    },
    {
        "name": "Maryellen Prince",
        "age": 25,
        "type": "student"
    },
    {
        "name": "Joyce Cline",
        "age": 20,
        "type": "student"
    },
    {
        "name": "Schroeder Weeks",
        "age": 26,
        "type": "student"
    },
    {
        "name": "Nieves Aguilar",
        "age": 30,
        "type": "student"
    },
    {
        "name": "Geraldine Mack",
        "age": 28,
        "type": "student"
    },
    {
        "name": "James Jacobson",
        "age": 25,
        "type": "teacher",
        "specialization": "computer science",
        "scientificWorksAmount": 0
    },
    {
        "name": "Eugenia Gaines",
        "age": 31,
        "type": "student"
    },
    {
        "name": "Taylor Mendoza",
        "age": 34,
        "type": "student"
    },
    {
        "name": "Felicia Robbins",
        "age": 20,
        "type": "teacher",
        "specialization": "computer science",
        "scientificWorksAmount": 0
    },
    {
        "name": "Morton Hayden",
        "age": 30,
        "type": "student"
    },
    {
        "name": "Claudia Davenport",
        "age": 26,
        "type": "student"
    },
    {
        "name": "Barnett Joseph",
        "age": 35,
        "type": "student"
    },
    {
        "name": "Reese Vazquez",
        "age": 39,
        "type": "admin"
    },
    {
        "name": "Soto Everett",
        "age": 28,
        "type": "student"
    },
    {
        "name": "Karin Carey",
        "age": 23,
        "type": "student"
    },
    {
        "name": "Garrett Faulkner",
        "age": 26,
        "type": "student"
    },
    {
        "name": "Ball Walton",
        "age": 37,
        "type": "student"
    },
    {
        "name": "Stella Cooper",
        "age": 27,
        "type": "student"
    },
    {
        "name": "Blanchard Collins",
        "age": 39,
        "type": "teacher",
        "specialization": "computer science",
        "scientificWorksAmount": 5
    },
    {
        "name": "Carolina Booker",
        "age": 35,
        "type": "student"
    },
    {
        "name": "Natalie Nieves",
        "age": 37,
        "type": "student"
    },
    {
        "name": "Travis Atkinson",
        "age": 29,
        "type": "student"
    },
    {
        "name": "Ebony Best",
        "age": 24,
        "type": "student"
    },
    {
        "name": "Amber Hayes",
        "age": 38,
        "type": "teacher",
        "specialization": "computer science",
        "scientificWorksAmount": 5
    },
    {
        "name": "Pacheco Buck",
        "age": 34,
        "type": "student"
    },
    {
        "name": "Franco Dudley",
        "age": 38,
        "type": "student"
    },
    {
        "name": "Green Young",
        "age": 37,
        "type": "student"
    },
    {
        "name": "Jennie Garrison",
        "age": 26,
        "type": "student"
    },
    {
        "name": "Traci Mccall",
        "age": 21,
        "type": "student"
    },
    {
        "name": "Dixie White",
        "age": 30,
        "type": "teacher",
        "specialization": "literature",
        "scientificWorksAmount": 10
    },
    {
        "name": "Garner Obrien",
        "age": 22,
        "type": "student"
    },
    {
        "name": "Figueroa Tate",
        "age": 21,
        "type": "teacher",
        "specialization": "history",
        "scientificWorksAmount": 6
    },
    {
        "name": "Vaughan Hunt",
        "age": 39,
        "type": "student"
    },
    {
        "name": "Gilliam Rivers",
        "age": 25,
        "type": "student"
    },
    {
        "name": "Gilda Hurley",
        "age": 21,
        "type": "teacher",
        "specialization": "jurisprudence",
        "scientificWorksAmount": 10
    },
    {
        "name": "Pruitt Battle",
        "age": 31,
        "type": "student"
    },
    {
        "name": "Lynda Huber",
        "age": 35,
        "type": "student"
    },
    {
        "name": "Henrietta Steele",
        "age": 32,
        "type": "student"
    },
    {
        "name": "Strickland Watkins",
        "age": 40,
        "type": "student"
    },
    {
        "name": "Blackburn Vaughan",
        "age": 28,
        "type": "student"
    },
    {
        "name": "Adele Dalton",
        "age": 27,
        "type": "student"
    },
    {
        "name": "Fox Lamb",
        "age": 39,
        "type": "student"
    },
    {
        "name": "Delgado Burks",
        "age": 40,
        "type": "student"
    },
    {
        "name": "Marcella Wall",
        "age": 24,
        "type": "student"
    },
    {
        "name": "Dolly Day",
        "age": 22,
        "type": "student"
    },
    {
        "name": "Ballard Rutledge",
        "age": 33,
        "type": "student"
    },
    {
        "name": "Tiffany Boyd",
        "age": 33,
        "type": "student"
    },
    {
        "name": "Richard Bernard",
        "age": 36,
        "type": "student"
    },
    {
        "name": "Lara Mckay",
        "age": 35,
        "type": "teacher",
        "specialization": "history",
        "scientificWorksAmount": 8
    },
    {
        "name": "Linda Holland",
        "age": 30,
        "type": "student"
    },
    {
        "name": "Peters Murray",
        "age": 32,
        "type": "student"
    },
    {
        "name": "Freeman Higgins",
        "age": 22,
        "type": "student"
    }
];